spring.application.name=websocket-service
server.port=8085

# RabbitMQ - Sync Broker (pentru notifications-queue)
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}


# Queue name
rabbitmq.queue.notifications=notifications-queue