spring.application.name=customer-support-service

# Server
server.port=8086

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


# Gemini API Configuration
# Gemini API Configuration
gemini.api.key=AIzaSyDYKWqDEqECCaf-vJitjCyeOh1b8hJRRrI
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent