# Device ID
device.id=1

# RabbitMQ Data Broker
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
rabbitmq.queue.name=device-data-queue

# Interval in minute
simulator.interval.minutes=10

# Consum de baza in Watts
simulator.base.load=1500.0